# -*- coding: utf-8 -*-
"""Studio_reddito_AQ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywIjOePaOly2yeZ7LX3Z5TlhregDs1_4
"""

import pandas as pd

anni = [2008,2011,2016,2021]
dati_redditi = []
### Specificare il percorso dei file (rinvenibili sul sito del MEF:
### https://www1.finanze.gov.it/finanze/analisi_stat/public/index.php?opendata=yes )
### Devo trovare dove sono accessibili tramite API o altro tipo di Query più comoda.
for i in range(len(anni)):
  percorso = '/content/Redditi_e_principali_variabili_IRPEF_su_base_comunale_CSV_' + str(anni[i]) + '.csv'
  dati = pd.read_csv(percorso,sep=';',index_col=False, encoding = "ISO-8859-1")
  dati_redditi.append(dati)

for i in range(len(dati_redditi)):
  dati_redditi[i].columns = dati_redditi[i].columns.str.replace("Ammontare in euro", "Ammontare")
  dati_redditi[i]['Reddito complessivo TOTALE'] = dati_redditi[i][[
       'Reddito complessivo minore o uguale a zero euro - Ammontare',
       'Reddito complessivo da 0 a 10000 euro - Ammontare',
       'Reddito complessivo da 10000 a 15000 euro - Ammontare',
       'Reddito complessivo da 15000 a 26000 euro - Ammontare',
       'Reddito complessivo da 26000 a 55000 euro - Ammontare',
       'Reddito complessivo da 55000 a 75000 euro - Ammontare',
       'Reddito complessivo da 75000 a 120000 euro - Ammontare',
       'Reddito complessivo oltre 120000 euro - Ammontare']].sum(axis=1)
  dati_redditi[i]['Contribuenti'] = dati_redditi[i][[
       'Reddito complessivo minore o uguale a zero euro - Frequenza',
       'Reddito complessivo da 0 a 10000 euro - Frequenza',
       'Reddito complessivo da 10000 a 15000 euro - Frequenza',
       'Reddito complessivo da 15000 a 26000 euro - Frequenza',
       'Reddito complessivo da 26000 a 55000 euro - Frequenza',
       'Reddito complessivo da 55000 a 75000 euro - Frequenza',
       'Reddito complessivo da 75000 a 120000 euro - Frequenza',
       'Reddito complessivo oltre 120000 euro - Frequenza']].sum(axis=1)
  dati_redditi[i] = dati_redditi[i][['Codice catastale', 'Reddito complessivo TOTALE','Contribuenti']]

url = 'https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.xls'
comuni = pd.read_excel(url)
comuni = comuni.rename(columns={'Denominazione in italiano':'Comune',
                       "Codice dell'Unità territoriale sovracomunale \n(valida a fini statistici)":"Codice provincia",
                       "Denominazione dell'Unità territoriale sovracomunale \n(valida a fini statistici)":"Nome provincia",
                       'Sigla automobilistica':"Provincia",
                       'Codice Catastale del comune':'Codice_catastale_comune',
                       'Denominazione Regione':'Regione',
                       'Flag Comune capoluogo di provincia/città metropolitana/libero consorzio':'Flag Capoluogo'})
# comuni = comuni[comuni['Flag Capoluogo']==1] # Per isolare solamente i capoluoghi di provincia

url = 'https://github.com/cfdenardis/cose_utili/raw/main/comuni_popolazione.csv'
comuni_popolazione = pd.read_csv(url)
try:
  comuni_popolazione = comuni_popolazione.drop('Unnamed: 0', axis=1)
except:
  pass
comuni = pd.merge(comuni,comuni_popolazione,how='left',left_on='Codice_catastale_comune',right_on='CODICE BELFIORE')
comuni_capoluogo = comuni_capoluogo[['Comune', 'Codice_catastale_comune', 'Regione', 'Codice Regione',
       'Nome provincia', 'Provincia', 'Codice provincia', 'Flag Capoluogo',
       'POPOLAZIONE']]

comuni_reddito = comuni
for i in range(len(dati_redditi)):
  comuni_reddito = pd.merge(
      comuni_reddito, dati_redditi[i],
      left_on='Codice_catastale_comune', right_on = 'Codice catastale',
      how='left').drop(columns='Codice catastale')
  descr_reddito_anno = 'Reddito ' + str(anni[i])
  descr_reddito_PC_anno = 'Reddito pro capite ' + str(anni[i])
  descr_contribuenti_anno = 'Contribuenti ' + str(anni[i])
  comuni_reddito = comuni_reddito.rename(columns={'Reddito complessivo TOTALE':descr_reddito_anno})
  comuni_reddito = comuni_reddito.rename(columns={'Contribuenti':descr_contribuenti_anno})
  comuni_reddito[descr_reddito_PC_anno] = comuni_reddito[descr_reddito_anno]/comuni_reddito[descr_contribuenti_anno]
  comuni_reddito = comuni_reddito.sort_values(by=descr_reddito_PC_anno,ascending=False).reset_index(drop = True)
  comuni_reddito['Classifica pro capite ' + str(anni[i])] = comuni_reddito.index + 1

for i in range(len(anni)-1):
  anno1 = anni[i]
  anno2 = anni[i+1]
  nome_col_variazione = 'Variazione PC ' + str(anno1) + '-' + str(anno2)
  comuni_reddito[nome_col_variazione] = comuni_reddito['Reddito pro capite ' + str(anno2)]/comuni_reddito['Reddito pro capite ' + str(anno1)]*100 - 100
  comuni_reddito = comuni_reddito.sort_values(by=nome_col_variazione,ascending=False).reset_index(drop = True)
  comuni_reddito['Classifica Variazione ' + str(anno1) + '-' + str(anno2)] = comuni_reddito.index + 1

### Un esempio
comuni_reddito[comuni_reddito['Codice_catastale_comune'] == 'A345']

comuni_reddito.to_excel('/content/comuni_reddito_confr_2008-2011-2016-2021.xlsx',index=False)